services:
  cache:
    alias: cache.filesystem

  cache.void:
    class: Cache\Adapter\Void\VoidCachePool

  cache.filesystem:
    class: Cache\Adapter\Filesystem\FilesystemCachePool
    arguments: ['@flysystem.filesystem']

  flysystem.filesystem:
    class: League\Flysystem\Filesystem
    arguments: ['@flysystem.local_adapter']

  flysystem.local_adapter:
    class: League\Flysystem\Adapter\Local
    arguments: ['%kernel.project_dir%/var/cache/%kernel.environment%/fs']

  middleware.cache:
    class: App\Middleware\Cache
    arguments: ['@cache']
    public: true

  middleware.security:
    class: App\Middleware\SecurityVoters
    public: true
    arguments:
      - ['@security.voter.admin', '@security.voter.image']

  security.voter.admin:
    class: App\Security\AdminVoter

  security.voter.image:
    class: App\Security\ImageVoter

  controller.startpage:
    class: App\Controller\StartpageController
    public: true

  controller.foo:
    class: App\Controller\FooController
    public: true
